config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  get 'users/current' => 'users#current'
  post 'images/upload' => 'images#upload'
  get 'images/all_images' => 'images#all_images'
  get 'images/images_update' => 'images#images_update'
  post 'users/update' => 'users#update'
  get 'users/:id/:name/:token' => 'users#show'
  get 'users/mailer' => 'users#mailer'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/image.rb
class Image < ActiveRecord::Base

  has_attached_file :image, styles: { medium: "700x700>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :user_id, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 5 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :images
  has_many :emails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def upload
    @user = current_user
    params[:images].each do |image|
      Image.create(image:image, user_id: @user.id)
    end
    @images = Image.where(user_id: @user.id)
    render :json => @images
  end

  def all_images
    @user = current_user
    @images = Image.where(user_id: @user.id).order(created_at: :desc)
    render :json => @images
  end

  def images_update
    @user = current_user
    @images = Image.where(user_id: @user.id).order(created_at: :desc)
    respond_to do |format|
      format.js
    end
  end


  private

  def image_params
    params.require(:image).permit(:image, :user_id)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(user_path(@user), notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @image = Image.new
  end

  def create
    @user = User.new(user_params)
    token = SecureRandom.hex[0,20].upcase
    @user.url_token = token
    if @user.save
      @user = login(user_params[:email], user_params[:password])
      redirect_to user_path(@user), notice: "User Created!"
    else
      flash.now[:alert] = "User Not Created"
      redirect_to user_new_path
    end
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user || params[:token] == @user.url_token
      if params[:token]
        @guest = true
        @name = params[:name]
      else
        @guest = false
      end
      @images = Image.where(user_id: @user.id)
    else
      flash.now[:alert] = "You do not have access to that user's photos"
      redirect_to root_path
    end
  end

  def current
    render :json => current_user
  end

  def update
    @user = current_user
    @user.update_attributes(first_name: params[:first_name],
                            last_name: params[:last_name],
                            email: params[:email])
    render nothing: true
  end

  def mailer
    email_string = params[:myEmail].join(", ")
    UserMailer.share_email(current_user, email_string).deliver_now
    render nothing: true
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/images_update.js.erb
 $("#image-wrapper").html("<%= escape_javascript(render partial: 'layouts/images', locals: { images: @images } ) %>"); 

app/views/layouts/_images.html.erb
<% images.each do |image| %>
  <div class="image-wrapper">
    <%=image_tag image.image.url(:medium), class: "image materialboxed " %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">Gallery Dump</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <% if current_user %>
        <li><%= link_to "#{current_user.first_name}", user_path(current_user) %></li>
        <li><%= link_to "Logout", :logout %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <% if current_user %>
        <li><%= link_to "#{current_user.first_name}", user_path(current_user) %></li>
        <li><%= link_to "Logout", :logout %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageLiker</title>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href=
    "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="http://ajax.aspnetcdn.com/ajax/knockout/knockout-3.3.0.js"></script>
</head>
<body>
<%= render "layouts/navbar" %>
<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<div class="whole-view">
  <div class="shade-layer">
    <div class="center-align">
      <h1 class="title">Gallery Dump</h1>
      <h5 class="description">Upload your images and share them with your friends and family</h5>
      <%= link_to "Sign Up", new_user_path, class: "waves-effect waves-light btn" %>
    </div>
  </div>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container-form">
  <%= form_tag user_sessions_path, :method => :post do %>
    <fieldset class="form-group">
      <%= label_tag :email %>
      <%= text_field_tag :email, nil, class: "form-control" %>
    </fieldset>
    <fieldset class="form-group">
      <%= label_tag :password %>
      <%= password_field_tag :password, nil, class: "form-control" %>
    </fieldset>
    <div>
      <%= submit_tag "Login", class: "btn btn-blue" %>
    </div>
  <% end %>
</div>

app/views/users/current.html.erb
<h1>ou made it</h1>

app/views/users/new.html.erb
<div class="container-form">
  <%= form_for @user do |f| %>
    <% if f.object.errors.any? %>
      <ul>
        <% f.object.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
      </ul>
    <% end %>
    <fieldset class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </fieldset>
    <div class="margin-10">
      <%= f.submit "Create User", class: "btn btn-blue" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col m6">
      <% if @guest %>
        <h1><%=@name%></h1>
      <% else %>
        <h1 data-bind="text: firstName"></h1>
      <% end %>
    </div>
    <div class="col m6">
      <% if !@guest %>
        <p>
          <a href="javascript:void(0)" data-bind="click: showImages">Images</a> |
          <a href="javascript:void(0)" data-bind="click: showShare">Share</a> |
          <a href="javascript:void(0)" data-bind="click: showEdit">Edit Personal Info</a>
        </p>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col s12">

      <% if !@guest %>
        <div id="user-edit" class="display-hide card-panel input-field">
          <fieldset class="form-group">
            <input data-bind="value: firstName" id="first_name"/>
          </fieldset>
          <fieldset class="form-group">
            <input data-bind="value: lastName" id="last_name"/>
          </fieldset>
          <fieldset class="form-group">
            <input data-bind="value: email" id="email"/>
          </fieldset>
          <input type="submit" class="btn btn-default" data-bind="click: hideEdit">
        </div>
      <% end %>

      <div id="image-show" class="full-width">
        <% if !@guest %>
          <div class="upload-form center-align">
            <input type="file" id="file-selected" name="images[]" multiple>
            <div class="btn btn-primary margin-10" data-bind="click: uploadImage">Upload Images</div>
          </div>
        <% end %>
        <div class="flex-wrapper" id="image-wrapper">
          <%= render partial: 'layouts/images', locals: {images: @images}  %>
        </div>
      </div>

      <% if !@guest %>
        <div class="display-hide email-form" id="email-share">
          <p>
            Let people see your photos! Add emails below for those you wish to
            share your images with. A link will be sent allowing them to view your
            gallery.
          </p>
          <table>
            <thead><tr>
                <th>Email</th>
            </tr></thead>
            <tbody data-bind="foreach: myEmails">
                <tr>
                    <td><input data-bind="value: email" class="margin-10"/></td>
                    <td><a href="#" data-bind="click: $root.removeEmail">Remove</a></td>
                </tr>
            </tbody>
          </table>
          <button data-bind="click: addEmail" class="btn btn-default">Add Email</button>
          <button data-bind="click: sendEmail" class="btn btn-primary">Share</button>
        </div>
      <% end %>
    </div>
  </div>

</div>